[package]
name = "mcpdebug"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
mcp-monitor = { path = "../mcp-monitor" }
mcp-proxy = { path = "../mcp-proxy" }