[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Only build binaries marked with dist = true
precisely-dist = ["mcp-probe"]
# Skip checking whether cargo-dist should be run
allow-dirty = ["ci"]

# Use latest GitHub runners
[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04"
x86_64-unknown-linux-gnu = "ubuntu-22.04"
x86_64-apple-darwin = "macos-13"
aarch64-apple-darwin = "macos-14"
